IMAGE_NAME = "ubuntu/jammy64"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = IMAGE_NAME

    # Port forwarding pro SSH
    ubuntu.vm.network "forwarded_port", guest: 22, host: 2202, host_ip: "127.0.0.1"

    # Druhá síťová karta s pevnou IP 192.168.1.3 (interní síť)
    ubuntu.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: true

    ubuntu.vm.hostname = "ubuntu"
  end

  # Kopírování SSH klíče (pokud chceš použít)
  config.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/me.pub"
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL

  # Provisioning tvých skriptů
  config.vm.provision "shell", path: "install-zabbix-agent2.sh"
  config.vm.provision "shell", path: "configure-zabbix-agent2.sh"
end
